# >>> Basic Setup | 基础设置 <<<

# Header | 主菜单
## About Page: `hexo new page about`
## Tags Cloud Page: `hexo new page tags`
menu:
  所有文章: /archives/
  分类&标签: /tags/
  我的读书: /books/
  我的电影: /movies/
##  我的豆瓣秀: /douban/
  树: /categories/tree/
  面试: /categories/interview/
  清单: /categories/lists/
  关于我: /aboutme/

# Link to your avatar | 填写头像地址
avatar: /img/logo.jpg

# Small icon of Your site | 站点小图标地址
favicon: /img/favicon.ico

# 域名是否启用https，如果启用，js文件必须https加载
isHttps: true

# Social info. Bar | 社交信息展示
## Keep "mailto:" in Email | 设置 Email 时保留 "mailto:"
## Encrypt email 加密邮件地址 http://ctrlq.org/encode/
## RSS requires a plugin to take effect | 使用 RSS 需先安装对应插件
## https://github.com/hexojs/hexo-generator-feed
Plugins:
- hexo-generator-feed
- hexo-generator-sitemap
- hexo-generator-baidu-sitemap
- hexo-douban

## 仅支持链接
subnav:
  github: https://github.com/ZhaoGitHub1/
  douban: https://www.douban.com/people/174692469/
#  rss: /atom.xml
#  mail: 183479916@qq.com
#  qq: 183479916
#  wechat: 16602139700
  zhihu: https://www.zhihu.com/people/yi-zhu-27-93/activities
#  weibo:
#  google:
#  linkedin:
#  facebook:
#  twitter:
#  stackoverflow:

# >>> Conments 评论系统 <<<
disqus:
  on: false
  shortname: xxxxxxxxx
  # https://help.disqus.com/customer/en/portal/articles/466208-what-s-a-shortname-
  # It is unnecessary to enable disqus here if
  # you have set "disqus_shortname" in your site's "_config.yml"
changyan:
  on: false
  appid: xxxx
  conf: xxxxxxxxx
  # 是否开启畅言评论，
  # id 中填写你的友言用户数字ID，注册后进入后台管理即可查看
  # 畅言评论在 Web 环境下运行，普通本地环境无法查看，请部署后在线上测试。
gitment:
  on: true
  githubID: ZhaoGitHub1
  repo: ZhaoGitHub1.github.io
  client_id: 0959e9fdfc97cef82968
  client_secret: 126454836d441306e61dfbf9bb3ddc6cef1bf93d
  lazy: true

# >>> Style Customisation 样式自定义 <<<

# Background | 背景
## "background_sum": show images form /source/background/的图片数目
## "on: true": 自动随机显示这5张图片
## "on: false": 自定义显示图片设置background_image: 5
background:
  on: true
  background_sum: 8
#  background_image: 1

highlight_style:
  on: true
  inline_code: 9  # Value: 0 - 9 可选
  code_block: 4  # Value: 0 - 4
  # Set inline_code to style highlight text
  # Chose a highlight theme for code block
  # 通过 inline_code 切换内置文本高亮样式
  # 通过 code_block 切换内置代码高亮配色主题

blockquote_style:
  #on: true
  blockquote: 5  # Value: 0 - 7 可选
  # 自定义文章「引用部分」的样式

# 左边栏宽度 px
left_col_width: 300

# 目录中标题不换行
# Keep TOC title on the same line |
toc_nowrap: false

# 自定义"阅读全文"链接按钮的显示文字
# Customize the text on excerpt link
excerpt_link: 查看全文 #修改more>>的文字

# 是否显示边栏中的搜索框（站内搜索）
# Search Box in left column
search_box: true
#search: 
#  path: search.xml
#  field: post
#  format: html
#  limit: 10000

# 是否开启主页及加载头像时的动画效果
# Animation in Homepage and Loading avatar
animate: true

# >>> Small features | 小功能设置 <<<

# 是否开启边栏多标签切换
# Birdhouse button in left column
tagcloud: true
categorycloud: true

# Blogroll, Link exchange | 友情链接
friends:
  Spring官网: https://spring.io/
  Mybatis官网: http://www.mybatis.org/mybatis-3/zh/index.html
  Hibernate官网: http://hibernate.org/
#是否开启“关于我”。
aboutme: 一名普通的java 后台开发工程师~~  邮箱：183479916@qq.com

# 是否在新窗口打开链接
open_in_new: false

# Customize feed link 自定义订阅地址
rss: /atom.xml
feed:
  type: atom
  path: atom.xml
  limit: 20
# >>> Vendors | 第三方工具 & 服务 <<<

# images viewer | 图片浏览器
## http://www.fancyapps.com/fancybox/
fancybox: true

# Display Math(LaTeX, MathML...) | 数学公式支持
## https://www.mathjax.org/
mathjax: true

# Socail Share | 是否开启分享
share: false
baidushare: false
showshare: false

# 百度、谷歌站长验证。填写 HTML 标签 content
# Site Verification for Google and Baidu. HTML label content.
# google_site: # pFW527fHrjfI0si2w4NQ0w3cTw12AvvuohAu1PUfqKA
# baidu_site: #c167b9feb4f0b208b712c79629c188e4

# Fill in Google Analytics tracking ID, #e.g. UA-XXXXX-X, or Baidu Analytics hash key
google_analytics: xxxxx
baidu_analytics: eb7d8cefd581790a3213e8feb93ae89f



# 不蒜子网站计数设置
# http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  on: false
  site_visit: 极客到访数
  page_visit: 本页阅读量


# A标签提示
TipTitle: true

# Loading
# Loading: true

# Local search
local_search:
  enable: true

post_wordcount: 
  item_text: true
  wordcount: true
  min2read: true